# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/malos/driver.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "matrix_malos.DriverConfig" do
    optional :delay_between_updates, :float, 1
    optional :timeout_after_last_ping, :float, 2
    optional :image, :message, 3, "matrix_malos.EverloopImage"
    optional :malos_eye_config, :message, 4, "matrix_malos.MalosEyeConfig"
    optional :zigbee_message, :message, 5, "matrix_malos.ZigBeeMsg"
    optional :lirc, :message, 6, "matrix_malos.LircParams"
    optional :servo, :message, 7, "matrix_malos.ServoParams"
    optional :gpio, :message, 8, "matrix_malos.GpioParams"
    optional :humidity, :message, 9, "matrix_malos.HumidityParams"
    optional :micarray, :message, 10, "matrix_malos.MicArrayParams"
  end
  add_message "matrix_malos.MalosEyeConfig" do
    optional :camera_config, :message, 1, "matrix_malos.CameraConfig"
    optional :detector_config, :message, 2, "matrix_malos.ObjectDetectorConfig"
    optional :tracker_config, :message, 3, "matrix_malos.TrackerConfig"
    optional :detection_server_config, :message, 4, "matrix_malos.DetectionServerConfig"
    repeated :object_to_detect, :enum, 21, "matrix_malos.EnumMalosEyeDetectionType"
  end
  add_message "matrix_malos.CameraConfig" do
    optional :camera_id, :int32, 1
    optional :width, :int32, 2
    optional :height, :int32, 3
  end
  add_message "matrix_malos.ObjectDetectorConfig" do
    optional :cascade_path, :string, 1
  end
  add_message "matrix_malos.TrackerConfig" do
    optional :frames_to_count, :int32, 1
    optional :frames_to_discard, :int32, 2
  end
  add_message "matrix_malos.DetectionServerConfig" do
    optional :detection_server_address, :string, 1
    optional :detection_server_timeout, :int32, 2
  end
  add_message "matrix_malos.DriverInfo" do
    optional :driver_name, :string, 1
    optional :base_port, :int32, 2
    optional :provides_updates, :bool, 3
    optional :delay_between_updates, :int32, 4
    optional :needs_pings, :bool, 5
    optional :timeout_after_last_ping, :int32, 6
    optional :notes_for_human, :string, 7
  end
  add_message "matrix_malos.MalosDriverInfo" do
    repeated :info, :message, 1, "matrix_malos.DriverInfo"
  end
  add_message "matrix_malos.Dummy" do
    optional :value, :float, 1
  end
  add_message "matrix_malos.Humidity" do
    optional :humidity, :float, 1
    optional :temperature, :float, 2
    optional :temperature_raw, :float, 3
    optional :temperature_is_calibrated, :bool, 4
  end
  add_message "matrix_malos.HumidityParams" do
    optional :current_temperature, :float, 1
  end
  add_message "matrix_malos.UV" do
    optional :uv_index, :float, 1
    optional :oms_risk, :string, 2
  end
  add_message "matrix_malos.Pressure" do
    optional :pressure, :float, 1
    optional :altitude, :float, 2
    optional :temperature, :float, 3
  end
  add_message "matrix_malos.Imu" do
    optional :yaw, :float, 1
    optional :pitch, :float, 2
    optional :roll, :float, 3
    optional :accel_x, :float, 4
    optional :accel_y, :float, 5
    optional :accel_z, :float, 6
    optional :gyro_x, :float, 7
    optional :gyro_y, :float, 8
    optional :gyro_z, :float, 9
    optional :mag_x, :float, 10
    optional :mag_y, :float, 11
    optional :mag_z, :float, 12
  end
  add_message "matrix_malos.LedValue" do
    optional :red, :uint32, 1
    optional :green, :uint32, 2
    optional :blue, :uint32, 3
    optional :white, :uint32, 4
  end
  add_message "matrix_malos.EverloopImage" do
    repeated :led, :message, 1, "matrix_malos.LedValue"
  end
  add_message "matrix_malos.ZigBeeMsg" do
    optional :type, :enum, 1, "matrix_malos.ZigBeeMsg.ZigBeeCmdType"
    optional :zcl_cmd, :message, 2, "matrix_malos.ZigBeeMsg.ZCLCmd"
    optional :network_mgmt_cmd, :message, 3, "matrix_malos.ZigBeeMsg.NetworkMgmtCmd"
  end
  add_message "matrix_malos.ZigBeeMsg.ZCLCmd" do
    optional :type, :enum, 1, "matrix_malos.ZigBeeMsg.ZCLCmd.ZCLCmdType"
    optional :onoff_cmd, :message, 2, "matrix_malos.ZigBeeMsg.ZCLCmd.OnOffCmd"
    optional :level_cmd, :message, 3, "matrix_malos.ZigBeeMsg.ZCLCmd.LevelCmd"
    optional :colorcontrol_cmd, :message, 4, "matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd"
    optional :identify_cmd, :message, 5, "matrix_malos.ZigBeeMsg.ZCLCmd.IdentifyCmd"
    optional :node_id, :uint32, 6
    optional :endpoint_index, :uint32, 7
  end
  add_message "matrix_malos.ZigBeeMsg.ZCLCmd.OnOffCmd" do
    optional :type, :enum, 1, "matrix_malos.ZigBeeMsg.ZCLCmd.OnOffCmd.ZCLOnOffCmdType"
  end
  add_enum "matrix_malos.ZigBeeMsg.ZCLCmd.OnOffCmd.ZCLOnOffCmdType" do
    value :ON, 0
    value :OFF, 1
    value :TOGGLE, 2
  end
  add_message "matrix_malos.ZigBeeMsg.ZCLCmd.LevelCmd" do
    optional :type, :enum, 1, "matrix_malos.ZigBeeMsg.ZCLCmd.LevelCmd.ZCLLevelCmdType"
    optional :move_to_level_params, :message, 2, "matrix_malos.ZigBeeMsg.ZCLCmd.LevelCmd.MoveToLevelCmdParams"
    optional :move_params, :message, 3, "matrix_malos.ZigBeeMsg.ZCLCmd.LevelCmd.MoveCmdParams"
  end
  add_message "matrix_malos.ZigBeeMsg.ZCLCmd.LevelCmd.MoveToLevelCmdParams" do
    optional :level, :uint32, 1
    optional :transition_time, :uint32, 2
  end
  add_message "matrix_malos.ZigBeeMsg.ZCLCmd.LevelCmd.MoveCmdParams" do
    optional :mode, :uint32, 1
    optional :rate, :uint32, 2
  end
  add_enum "matrix_malos.ZigBeeMsg.ZCLCmd.LevelCmd.ZCLLevelCmdType" do
    value :MOVE_TO_LEVEL, 0
    value :MOVE, 1
  end
  add_message "matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd" do
    optional :type, :enum, 1, "matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.ZCLColorControlCmdType"
    optional :movetohue_params, :message, 2, "matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToHueCmdParams"
    optional :movetosat_params, :message, 3, "matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToSatCmdParams"
    optional :movetohueandsat_params, :message, 4, "matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToHueAndSatCmdParams"
  end
  add_message "matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToHueCmdParams" do
    optional :hue, :uint32, 1
    optional :direction, :enum, 2, "matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToHueCmdParams.DirectionParam"
    optional :transition_time, :uint32, 3
  end
  add_enum "matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToHueCmdParams.DirectionParam" do
    value :SHORTEST_DISTANCE, 0
    value :LONGEST_DISTANCE, 1
    value :UP, 2
    value :DOWN, 3
  end
  add_message "matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToSatCmdParams" do
    optional :saturation, :uint32, 1
    optional :transition_time, :uint32, 2
  end
  add_message "matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToHueAndSatCmdParams" do
    optional :hue, :uint32, 1
    optional :saturation, :uint32, 2
    optional :transition_time, :uint32, 3
  end
  add_enum "matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.ZCLColorControlCmdType" do
    value :MOVETOHUE, 0
    value :MOVETOSAT, 1
    value :MOVETOHUEANDSAT, 2
  end
  add_message "matrix_malos.ZigBeeMsg.ZCLCmd.IdentifyCmd" do
    optional :type, :enum, 1, "matrix_malos.ZigBeeMsg.ZCLCmd.IdentifyCmd.ZCLIdentifyCmdType"
    optional :identify_on_params, :message, 2, "matrix_malos.ZigBeeMsg.ZCLCmd.IdentifyCmd.IdentifyOnCmdParams"
    optional :identify_off_params, :message, 3, "matrix_malos.ZigBeeMsg.ZCLCmd.IdentifyCmd.IdentifyOffCmdParams"
  end
  add_message "matrix_malos.ZigBeeMsg.ZCLCmd.IdentifyCmd.IdentifyOnCmdParams" do
    optional :endpoint, :uint32, 1
    optional :identify_time, :uint32, 2
  end
  add_message "matrix_malos.ZigBeeMsg.ZCLCmd.IdentifyCmd.IdentifyOffCmdParams" do
    optional :identify_time, :uint32, 1
  end
  add_enum "matrix_malos.ZigBeeMsg.ZCLCmd.IdentifyCmd.ZCLIdentifyCmdType" do
    value :IDENTIFY_ON, 0
    value :IDENTIFY_OFF, 1
  end
  add_enum "matrix_malos.ZigBeeMsg.ZCLCmd.ZCLCmdType" do
    value :ON_OFF, 0
    value :LEVEL, 1
    value :COLOR_CONTROL, 2
    value :IDENTIFY, 3
  end
  add_message "matrix_malos.ZigBeeMsg.NetworkMgmtCmd" do
    optional :type, :enum, 1, "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NetworkMgmtCmdTypes"
    optional :permit_join_params, :message, 2, "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.PermitJoinParams"
    optional :is_proxy_active, :bool, 3
    optional :node_leave_params, :message, 4, "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NodeLeaveNetParams"
    optional :node_info, :message, 5, "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NodeDescription"
    repeated :connected_nodes, :message, 6, "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NodeDescription"
    optional :network_status, :message, 7, "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NetworkStatus"
  end
  add_message "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.PermitJoinParams" do
    optional :time, :uint32, 1
  end
  add_message "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NodeLeaveNetParams" do
    optional :node_id, :uint32, 1
  end
  add_message "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.ClusterDescription" do
    optional :type, :enum, 1, "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.ClusterDescription.ClusterInOutType"
    optional :cluster_id, :uint32, 2
  end
  add_enum "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.ClusterDescription.ClusterInOutType" do
    value :SERVER_IN, 0
    value :CLIENT_OUT, 1
  end
  add_message "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.EndPointDescription" do
    optional :endpoint_index, :uint32, 1
    optional :profile_id, :uint32, 2
    optional :device_id, :uint32, 3
    repeated :clusters, :message, 4, "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.ClusterDescription"
  end
  add_message "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NodeDescription" do
    optional :node_id, :uint32, 1
    optional :eui64, :uint64, 2
    repeated :endpoints, :message, 3, "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.EndPointDescription"
  end
  add_message "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NetworkStatus" do
    optional :type, :enum, 1, "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NetworkStatus.Status"
  end
  add_enum "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NetworkStatus.Status" do
    value :NO_NETWORK, 0
    value :JOINING_NETWORK, 1
    value :JOINED_NETWORK, 2
    value :JOINED_NETWORK_NO_PARENT, 3
    value :LEAVING_NETWORK, 4
  end
  add_enum "matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NetworkMgmtCmdTypes" do
    value :CREATE_NWK, 0
    value :LEAVE_NWK, 1
    value :NODE_LEAVE_NWK, 2
    value :PERMIT_JOIN, 3
    value :DISCOVERY_INFO, 4
    value :RESET_PROXY, 5
    value :IS_PROXY_ACTIVE, 6
    value :NETWORK_STATUS, 7
  end
  add_enum "matrix_malos.ZigBeeMsg.ZigBeeCmdType" do
    value :ZCL, 0
    value :NETWORK_MGMT, 1
  end
  add_message "matrix_malos.LircParams" do
    optional :device, :string, 1
    optional :command, :string, 2
    optional :config, :string, 3
  end
  add_message "matrix_malos.ServoParams" do
    optional :pin, :uint32, 1
    optional :angle, :uint32, 2
  end
  add_message "matrix_malos.GpioParams" do
    optional :pin, :uint32, 1
    optional :mode, :enum, 2, "matrix_malos.GpioParams.EnumMode"
    optional :value, :uint32, 3
    optional :values, :uint32, 4
  end
  add_enum "matrix_malos.GpioParams.EnumMode" do
    value :INPUT, 0
    value :OUTPUT, 1
  end
  add_message "matrix_malos.MicArrayParams" do
    optional :gain, :int32, 1
    optional :azimutal_angle, :float, 2
    optional :polar_angle, :float, 3
    optional :radial_distance_mm, :float, 4
    optional :sound_speed_mmseg, :float, 5
  end
  add_enum "matrix_malos.EnumMalosEyeDetectionType" do
    value :STOP, 0
    value :FACE, 20
    value :FACE_DEMOGRAPHICS, 21
    value :FACE_DESCRIPTOR, 30
    value :HAND_THUMB_UP, 40
    value :HAND_PALM, 41
    value :HAND_PINCH, 42
    value :HAND_FIST, 43
  end
end

module MatrixMalos
  DriverConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.DriverConfig").msgclass
  MalosEyeConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.MalosEyeConfig").msgclass
  CameraConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.CameraConfig").msgclass
  ObjectDetectorConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ObjectDetectorConfig").msgclass
  TrackerConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.TrackerConfig").msgclass
  DetectionServerConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.DetectionServerConfig").msgclass
  DriverInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.DriverInfo").msgclass
  MalosDriverInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.MalosDriverInfo").msgclass
  Dummy = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.Dummy").msgclass
  Humidity = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.Humidity").msgclass
  HumidityParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.HumidityParams").msgclass
  UV = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.UV").msgclass
  Pressure = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.Pressure").msgclass
  Imu = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.Imu").msgclass
  LedValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.LedValue").msgclass
  EverloopImage = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.EverloopImage").msgclass
  ZigBeeMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg").msgclass
  ZigBeeMsg::ZCLCmd = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd").msgclass
  ZigBeeMsg::ZCLCmd::OnOffCmd = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.OnOffCmd").msgclass
  ZigBeeMsg::ZCLCmd::OnOffCmd::ZCLOnOffCmdType = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.OnOffCmd.ZCLOnOffCmdType").enummodule
  ZigBeeMsg::ZCLCmd::LevelCmd = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.LevelCmd").msgclass
  ZigBeeMsg::ZCLCmd::LevelCmd::MoveToLevelCmdParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.LevelCmd.MoveToLevelCmdParams").msgclass
  ZigBeeMsg::ZCLCmd::LevelCmd::MoveCmdParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.LevelCmd.MoveCmdParams").msgclass
  ZigBeeMsg::ZCLCmd::LevelCmd::ZCLLevelCmdType = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.LevelCmd.ZCLLevelCmdType").enummodule
  ZigBeeMsg::ZCLCmd::ColorControlCmd = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd").msgclass
  ZigBeeMsg::ZCLCmd::ColorControlCmd::MoveToHueCmdParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToHueCmdParams").msgclass
  ZigBeeMsg::ZCLCmd::ColorControlCmd::MoveToHueCmdParams::DirectionParam = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToHueCmdParams.DirectionParam").enummodule
  ZigBeeMsg::ZCLCmd::ColorControlCmd::MoveToSatCmdParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToSatCmdParams").msgclass
  ZigBeeMsg::ZCLCmd::ColorControlCmd::MoveToHueAndSatCmdParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToHueAndSatCmdParams").msgclass
  ZigBeeMsg::ZCLCmd::ColorControlCmd::ZCLColorControlCmdType = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.ColorControlCmd.ZCLColorControlCmdType").enummodule
  ZigBeeMsg::ZCLCmd::IdentifyCmd = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.IdentifyCmd").msgclass
  ZigBeeMsg::ZCLCmd::IdentifyCmd::IdentifyOnCmdParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.IdentifyCmd.IdentifyOnCmdParams").msgclass
  ZigBeeMsg::ZCLCmd::IdentifyCmd::IdentifyOffCmdParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.IdentifyCmd.IdentifyOffCmdParams").msgclass
  ZigBeeMsg::ZCLCmd::IdentifyCmd::ZCLIdentifyCmdType = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.IdentifyCmd.ZCLIdentifyCmdType").enummodule
  ZigBeeMsg::ZCLCmd::ZCLCmdType = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZCLCmd.ZCLCmdType").enummodule
  ZigBeeMsg::NetworkMgmtCmd = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.NetworkMgmtCmd").msgclass
  ZigBeeMsg::NetworkMgmtCmd::PermitJoinParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.NetworkMgmtCmd.PermitJoinParams").msgclass
  ZigBeeMsg::NetworkMgmtCmd::NodeLeaveNetParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NodeLeaveNetParams").msgclass
  ZigBeeMsg::NetworkMgmtCmd::ClusterDescription = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.NetworkMgmtCmd.ClusterDescription").msgclass
  ZigBeeMsg::NetworkMgmtCmd::ClusterDescription::ClusterInOutType = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.NetworkMgmtCmd.ClusterDescription.ClusterInOutType").enummodule
  ZigBeeMsg::NetworkMgmtCmd::EndPointDescription = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.NetworkMgmtCmd.EndPointDescription").msgclass
  ZigBeeMsg::NetworkMgmtCmd::NodeDescription = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NodeDescription").msgclass
  ZigBeeMsg::NetworkMgmtCmd::NetworkStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NetworkStatus").msgclass
  ZigBeeMsg::NetworkMgmtCmd::NetworkStatus::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NetworkStatus.Status").enummodule
  ZigBeeMsg::NetworkMgmtCmd::NetworkMgmtCmdTypes = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.NetworkMgmtCmd.NetworkMgmtCmdTypes").enummodule
  ZigBeeMsg::ZigBeeCmdType = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ZigBeeMsg.ZigBeeCmdType").enummodule
  LircParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.LircParams").msgclass
  ServoParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.ServoParams").msgclass
  GpioParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.GpioParams").msgclass
  GpioParams::EnumMode = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.GpioParams.EnumMode").enummodule
  MicArrayParams = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.MicArrayParams").msgclass
  EnumMalosEyeDetectionType = Google::Protobuf::DescriptorPool.generated_pool.lookup("matrix_malos.EnumMalosEyeDetectionType").enummodule
end
