# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vision_service.proto

require 'google/protobuf'

require 'vision_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "admobilize_vision.VisionRequest" do
    optional :image, :bytes, 1
    repeated :detection, :enum, 2, "admobilize_vision.EnumDetectionTag"
    repeated :recognition, :enum, 3, "admobilize_vision.EnumFacialRecognitionTag"
    optional :image_list, :message, 4, "admobilize_vision.ImageList"
    optional :video, :message, 5, "admobilize_vision.Video"
  end
end

module AdmobilizeVision
  VisionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("admobilize_vision.VisionRequest").msgclass
end
